### ISSUE TITLE
Cannot process flags argument with a compiled pattern

### ISSUE THREAD

**Issue by jniggemann** [ClockworkNet/wtop#7]
```
machine:/tmp/logfiles# logrep -f 'status>399' -o 'count(*),status,url' -s '10:1' logfile.log 
Traceback (most recent call last):
  File "/usr/local/bin/logrep", line 5, in <module>
    pkg_resources.run_script('wtop==0.7.9', 'logrep')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/EGG-INFO/scripts/logrep", line 427, in <module>
    runit()
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/EGG-INFO/scripts/logrep", line 401, in runit
    order_descending, x_tmp_file)
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/logrep.py", line 1026, in calculate_aggregates
    for r in reqs:
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/logrep.py", line 810, in fn
    first = lst.next()
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/logrep.py", line 479, in iis_field_map
    for record in log:
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/logrep.py", line 491, in <genexpr>
    log = (dict(zip(cols, urllib.unquote_plus(t))) for t in tuples)
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/logrep.py", line 490, in <genexpr>
    tuples = (line.split(" ") for line in loglines)
  File "/usr/local/lib/python2.7/dist-packages/wtop-0.7.9-py2.7.egg/logrep.py", line 717, in line_exclude
    r = re.compile(pat, re.I)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 235, in _compile
    raise ValueError('Cannot process flags argument with a compiled pattern')
ValueError: Cannot process flags argument with a compiled pattern
```

**Comment by TimZehta** [comment]
Unfortunately, I am unable to reproduce the issue you encountered.

What does your config file look like?

What method did you use to install wtop?

**Comment by jniggemann** [comment]
I can't remember... IIRC, I installed from source (0.7.9) using `python setup.py install`...
Right now, I can't reproduce either -> closing.
